sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install: pip install tox coveralls wheel
script: tox -e $TOXENV
after_success: coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/96fe756871cf1399efe6
    on_success: change
    on_failure: always
    on_start: never
