sudo: false
language: python
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-django-111
    - python: 2.7
      env: TOXENV=py27-django-110
    - python: 2.7
      env: TOXENV=py27-django-19
    - python: 2.7
      env: TOXENV=py27-django-18
    - python: 3.5
      env: TOXENV=py35-django-111
    - python: 3.5
      env: TOXENV=py35-django-110
    - python: 3.5
      env: TOXENV=py35-django-19
    - python: 3.5
      env: TOXENV=py35-django-18
    - python: 3.6
      env: TOXENV=py36-django-111
    - python: 3.6
      env: TOXENV=py36-django-110
    - python: 3.6
      env: TOXENV=py36-django-19
    - python: 3.6
      env: TOXENV=py36-django-18
    - env: TOXENV=lint
    - env: TOXENV=readme
install: travis_retry pip install tox coveralls wheel
script: tox -v -- -v
after_success: coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/96fe756871cf1399efe6
    on_success: change
    on_failure: always
    on_start: never
